name: Run Lint and Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      - name: npm lint
        run: |
          npm run lint
        env:
          CI: true
      - name: npm test
        run: |
          npm test
        env:
          CI: true
